name: Lifetime IPO Tracker
on:
  schedule:
    - cron: '30 14 * * 1-5' 
  workflow_dispatch: 

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write 
      
    steps:
      - uses: actions/checkout@v4 
      
      - uses: actions/setup-python@v5 
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        # Swapped cloudscraper for curl_cffi
        run: pip install pandas curl_cffi lxml html5lib beautifulsoup4
        
      - name: Run Upsert Script
        run: python scraper.py
        
      - name: Commit and Push Archive
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add ipo_tracker.csv
          git commit -m "Automated IPO archive update" || exit 0
          git push
